'use strict';
const D=window.SENTINEL_DATA;
const state={page:'brief',line:'Prepaid',tab:'pending',report:'churn',failed:false,segment:'all',reportFrom:'',reportTo:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const published=D.runs.filter(r=>r.qualityGateStatus==='PASS'&&r.runStatus==='PUBLISHED').sort((a,b)=>a.scoredAtTs.localeCompare(b.scoredAtTs));
const run=published.at(-1),previous=published.at(-2),high=run.predictions.filter(p=>p.riskBand==='HIGH');
const newly=high.filter(p=>previous.predictions.some(q=>q.serviceInstanceId===p.serviceInstanceId&&q.riskBand!=='HIGH')).length;
const protectedCount=new Set(D.outcomes.filter(o=>o.status==='RETAINED'&&o.windowEndTs<=run.dataAsOfTs&&D.interventions.some(i=>i.interventionId===o.interventionId&&i.serviceInstanceId===o.serviceInstanceId&&published.some(r=>r.scoredAtTs<i.trackedAtTs&&r.predictions.some(p=>p.serviceInstanceId===i.serviceInstanceId&&p.riskBand==='HIGH')))).map(o=>o.serviceInstanceId)).size;
const date=v=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Kabul'}).format(new Date(v));
const pct=(n,d)=>d?(n/d*100).toFixed(1)+'%':'0%';
const campaigns=[{id:'C01',reportDate:'2026-09-22',name:'Recharge recovery',segment:'Recharge lapsing',status:'pending',audience:2,offer:'100 MB bonus after a qualifying recharge',channel:'SMS',budget:1,cost:.6,why:'Two scored subscribers in Recharge lapsing are high risk. A targeted recharge offer is proposed for review.',history:[]},{id:'C02',reportDate:'2026-09-22',name:'Usage recovery',segment:'Usage declining',status:'progress',audience:2,offer:'100 MB engagement bonus',channel:'SMS',budget:1,cost:.4,why:'A sample engagement campaign for declining usage.',history:[{action:'Approved',comment:'Seeded demonstration record',time:'22 Sep 2026',reviewer:'CVM team'}]},{id:'C03',reportDate:'2026-09-15',name:'Recharge reminder',segment:'Recharge lapsing',status:'history',audience:2,offer:'Recharge reminder without discount',channel:'SMS',budget:0,cost:0,why:'A completed demonstration of a reminder campaign.',history:[{action:'Completed (simulation)',comment:'No live messages sent. Retention uplift is not measured.',time:'15 Sep 2026',reviewer:'CVM team'}]}];
const names={brief:'Executive Brief',decisions:'My Decisions',reports:'Reports'};
const reportNames={churn:'Weekly Churn Summary',segments:'Segment Risk',campaigns:'Campaign Performance',subscribers:'At-Risk Subscribers',business:'Weekly Business Performance'};
const $=s=>document.querySelector(s);
function table(headers,rows,extra=''){return `<div class="table-wrap"><table ${extra}><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function toolbar(extra=''){return `<div class="toolbar"><div class="toolbar-left"><label class="field">Business line<select id="business-line">${['Prepaid','Postpaid','Fibre'].map(v=>`<option ${v===state.line?'selected':''}>${v}</option>`).join('')}</select></label>${extra}</div><span class="data-date">Data as of ${date(run.dataAsOfTs)} · AFT</span></div>`;}
function footer(){return `<footer class="footer">Published synthetic data <span class="pipe">|</span> <button class="link-button" data-provenance>View provenance</button> <span class="pipe">|</span> Client demonstration</footer>`;}
function empty(){return `<div class="panel empty"><h2>No data available</h2><p>${esc(state.line)} is available in the template. Its data and workflows have not been configured.</p></div>`;}
function segmentRows(){return D.segments.map(s=>{const a=run.predictions.filter(p=>p.microSegmentId===s.id),h=a.filter(p=>p.riskBand==='HIGH').length;return [esc(s.name),a.length,h,`<div class="risk"><span>${pct(h,high.length)}</span><div class="track"><div class="fill" style="width:${h/high.length*100}%"></div></div></div>`];});}
function legacyBrief(){const hour=Number(new Intl.DateTimeFormat('en-GB',{hour:'numeric',hourCycle:'h23',timeZone:'Asia/Kabul'}).format(new Date()));const greeting=hour>=5&&hour<12?'morning':hour<17&&hour>=12?'afternoon':'evening';
const stats=[['High-risk subscribers',high.length,'30-day predicted churn risk'],['Newly at risk',newly,'Moved into high risk since last run'],['High-risk share',pct(high.length,run.predictions.length),'Of all scored subscribers'],['Subscribers scored',run.predictions.length,'Published scoring population'],['Subscribers protected',protectedCount,'Completed retained outcome windows']];
const trend=published.map(r=>r.predictions.filter(p=>p.riskBand==='HIGH').length),points=trend.map((n,i)=>`${65+i*185},${160-n*16}`).join(' ');
const reasons=Object.entries(high.reduce((a,p)=>(a[p.primaryReason]=(a[p.primaryReason]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);
return `<h1>Good ${greeting}, Sunil.</h1><p class="page-sub">Your executive view of churn risk and retention activity.</p>${toolbar()}${state.line!=='Prepaid'?empty():`${state.failed?'<div class="fallback">Latest run did not pass publication checks. Showing the last published run from 22 Sep 2026.</div>':''}<div class="kpis">${stats.map(s=>`<div class="kpi"><div class="label">${s[0]}</div><div class="value">${s[1]}</div><div class="caption">${s[2]}</div></div>`).join('')}</div><section class="section"><div class="section-heading"><h2>Risk over time</h2><span class="meta">High-risk subscribers · weekly</span></div><div class="panel chart-panel"><svg class="trend" viewBox="0 0 680 205" role="img" aria-label="High-risk subscribers: 4 on 1 Sep, 5 on 8 Sep, 4 on 15 Sep, 7 on 22 Sep"><path class="grid" d="M55 32H635 M55 96H635 M55 160H635"/><text x="25" y="37">8</text><text x="25" y="101">4</text><text x="25" y="165">0</text><polyline class="line" points="${points}"/>${trend.map((n,i)=>`<circle class="dot" cx="${65+i*185}" cy="${160-n*16}" r="4"/><text x="${65+i*185}" y="${147-n*16}" text-anchor="middle">${n}</text><text x="${65+i*185}" y="192" text-anchor="middle">${1+i*7} Sep</text>`).join('')}</svg></div></section><section class="section"><div class="section-heading"><h2>Where risk is concentrated</h2><span class="meta" title="Segment high-risk count divided by all 7 high-risk subscribers.">Share of total high risk</span></div><div class="panel">${table(['Micro-segment','Scored','High risk','Risk share'],segmentRows())}</div></section><section class="section"><div class="section-heading"><h2>Top reasons</h2><span class="meta">Among high-risk subscribers</span></div><div class="panel reason-list">${reasons.map(([name,n])=>`<div class="reason"><span>${esc(name)}</span><div class="bar"><div style="width:${n/high.length*100}%"></div></div><strong>${n}</strong></div>`).join('')}</div></section><div class="panel map-summary"><div><h2>Churn risk map</h2><p class="section-sub">Explore segments, signals and predicted risk in one view.</p></div><button class="button primary" data-map>Explore risk map →</button></div><p class="meta" style="margin-top:12px">Protected counts reflect observed retained outcomes after tracked interventions. They do not establish campaign causality.</p>`}${footer()}`;}
function decisions(){return `<h1>My Decisions</h1><p class="page-sub">Review a recommendation. Approve a campaign. Track its progress.</p>${toolbar('<label class="field">Use case<select><option>Churn</option><option disabled>Revenue · not configured</option><option disabled>Growth · not configured</option></select></label>')}${state.line!=='Prepaid'?empty():`<div class="simulation">Demo workflow · Decisions are simulated and reset when you reload. No campaign is executed.</div><div class="tabs" role="tablist" aria-label="Campaign status">${[['pending','Pending approval'],['progress','In progress'],['history','History']].map(([k,v])=>`<button role="tab" aria-selected="${state.tab===k}" class="tab ${state.tab===k?'active':''}" data-tab="${k}">${v} <span class="count">${campaigns.filter(c=>c.status===k).length}</span></button>`).join('')}</div><div class="panel">${campaigns.filter(c=>c.status===state.tab).length?table(['Recommended campaign','Audience','Owner','Status',''],campaigns.filter(c=>c.status===state.tab).map(c=>[`<strong class="campaign-name">${c.name}</strong><br><span class="meta">${c.segment} · Churn</span>`,`${c.audience} subscribers`,'CVM team',`<span class="status ${c.status==='progress'?'ok':'neutral'}">${c.status==='pending'?'Needs approval':c.status==='progress'?'Queued / simulated':'Reviewed'}</span>`,`<button class="button" data-review="${c.id}">Review →</button>`])):'<div class="empty"><h2>You’re all caught up</h2><p>No campaigns in this view.</p></div>'}</div><p class="meta" style="margin-top:18px">Routine approvals go to the CVM team. Budget or policy exceptions can be routed to a CXO through operator configuration.</p>`}${footer()}`;}
function reportData(){if(state.report==='business')return biExportData();
const snapshot=reportSnapshot(),predictions=snapshot?.predictions||[],risk=predictions.filter(p=>p.riskBand==='HIGH');
if(state.report==='churn')return {headers:['Week','Scored','High risk','High-risk share','Newly at risk'],rows:reportRuns().map(r=>{const i=published.indexOf(r),h=r.predictions.filter(p=>p.riskBand==='HIGH'),w=reportWeek(r.scoredAtTs);return [hasReportDates()?reportPeriodLabel(w.start,w.end):date(r.dataAsOfTs),r.predictions.length,h.length,pct(h.length,r.predictions.length),i?h.filter(p=>published[i-1].predictions.some(q=>q.serviceInstanceId===p.serviceInstanceId&&q.riskBand!=='HIGH')).length:'—'];})};
if(state.report==='segments')return {headers:['Segment','Scored','High risk','Share of all high risk'],rows:snapshot?D.segments.map(s=>{const a=predictions.filter(p=>p.microSegmentId===s.id),h=a.filter(p=>p.riskBand==='HIGH').length;return [s.name,a.length,h,pct(h,risk.length)];}):[]};
if(state.report==='campaigns')return {headers:['Campaign','Audience','Status','Budget · USD','Actual spend','Measured uplift',...(hasReportDates()?['Activity date']:[])],rows:reportCampaigns().map(c=>[c.name,c.audience,c.status==='pending'?'Pending approval':c.status==='progress'?'Queued (simulation)':'Completed (simulation)',c.budget.toFixed(2),'Not available','Not measured',...(hasReportDates()?[reportDateLabel(c.reportDate)]:[])])};
return {headers:['Masked service ID','Segment','Risk','Predicted probability','Primary reason'],rows:risk.map(p=>['SVC-••••'+p.serviceInstanceId.slice(-4),p.microSegmentName,p.riskBand,pct(p.calibratedChurnProbability,1),p.primaryReason])};}
function reports(){if(state.report==='business')return businessReport();const r=reportData();return `<h1>Reports</h1><p class="page-sub">A clear view of risk, campaign activity and business performance.</p>${toolbar(`<label class="field">Report<select id="report-select">${Object.entries(reportNames).map(([k,v])=>`<option value="${k}" ${state.report===k?'selected':''}>${v}</option>`).join('')}</select></label>`)}${reportDateControls()}${reportRangeNote()}${state.line!=='Prepaid'?empty():`<div class="section-heading"><div><h2>${reportNames[state.report]}</h2><p class="section-sub">${state.report==='campaigns'?'Simulated campaign activity':`Published COM01 synthetic data · ${reportSnapshotNote()}`}</p></div><div class="actions"><button class="button" data-export ${r.rows.length?'':'disabled'}>Download Excel (.xlsx)</button><button class="button" data-print>Print / Save PDF</button></div></div>${r.rows.length?`<div class="panel report">${table(r.headers,r.rows.map(row=>row.map(esc)))}</div><div class="panel observations" style="margin-top:22px"><h3>What this tells us</h3><p>${reportObservation()}</p></div>`:reportNoData()}`}${footer()}`;}
function render(){if(window.SENTINEL_MART?.active){window.SENTINEL_MART.render();return;}const route=location.hash.slice(1).split('/');state.page=route[0];if(state.page==='reports'&&reportNames[route[1]])state.report=route[1];if(!names[state.page])state.page='brief';prepareBriefShell();$('#main').innerHTML=({brief,decisions,reports}[state.page])();document.querySelectorAll('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===state.page));document.title=`${names[state.page]} · Sentinel Studio`;$('#pulse-context').textContent=state.page==='brief'?`COM01 · Churn context (${state.line})`:`${names[state.page]} · ${state.line}`;$('#pulse-input').placeholder=state.page==='brief'?'Ask about published COM01 data…':'Ask about this demo…';const q=state.page==='brief'?briefQuestions:state.page==='decisions'?['What needs my approval?','What happens after approval?']:state.page==='reports'?(state.report==='business'?['How did revenue change this week?','What data sources feed this report?','Does this report require ML or AI?','What happened to actual churn?']:['What does this report show?','Is revenue part of the churn model?']):['Where is churn risk concentrated?','Why are subscribers at risk?','What does protected mean?'];$('#pulse-questions').innerHTML=q.map(v=>`<button class="question" data-question="${esc(v)}">${v}</button>`).join('');$('#pulse-conversation').innerHTML='';}
function modal(title,body){$('#detail-dialog').classList.remove('churn-dialog');$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=`<div class="dialog-body">${body}</div>`;$('#detail-dialog').showModal();}
function review(id){const c=campaigns.find(c=>c.id===id);if(!c)return;modal(c.name,`<div class="review-header"><span class="status neutral">${c.status==='pending'?'Pending approval':'Demo record'}</span><p class="section-sub">Churn · ${c.segment} · ${state.line}</p></div><div class="review-body"><h3>Why Sentinel suggests this</h3><p>${c.why}</p><dl class="detail-list">${[['Audience',`${c.audience} eligible subscribers · excludes opt-outs and active offers`],['Proposed offer',c.offer],['Channel / duration',`${c.channel} · 7 days after activation`],['Maximum offer cost',`USD ${c.cost.toFixed(2)} · Budget USD ${c.budget.toFixed(2)}`],['Approval owner','CVM team · CXO escalation for policy exceptions'],['Evidence',`${run.scoringRunId} · 30-day risk horizon`]].map(([k,v])=>`<div class="detail-row"><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><div class="checks">Sample checks: consent, offer eligibility and budget reviewed in the proposed workflow. Live checks are not connected.</div>${c.status==='pending'?`<label class="field" style="margin-top:20px">Review comment<textarea id="review-comment" rows="3" placeholder="Required when requesting changes or rejecting"></textarea></label><div class="actions review-actions"><button class="button primary" data-decision="approve" data-id="${id}">Approve campaign</button><button class="button" data-decision="change" data-id="${id}">Request changes</button><button class="button danger" data-decision="reject" data-id="${id}">Reject</button></div><p id="review-error" role="alert"></p>`:''}${c.history.length?`<h3 style="margin-top:24px">Review history</h3>${c.history.map(h=>`<p style="margin-top:12px"><strong>${esc(h.action)}</strong> · ${esc(h.time)} · ${esc(h.reviewer)}<br>${esc(h.comment)}</p>`).join('')}`:''}<p class="simulation" style="margin-top:18px">Simulation only. Approval queues a demo campaign and does not send messages, commit spend or change retention outcomes.</p></div>`);}
function decide(id,action,comment){const c=campaigns.find(c=>c.id===id);if(!c||c.status!=='pending'||!['approve','change','reject'].includes(action))throw Error('Decision is not available');if(action!=='approve'&&!comment.trim())throw Error('Add a comment before requesting changes or rejecting.');c.reportDate=new Date().toISOString().slice(0,10);c.status=action==='approve'?'progress':'history';c.history.push({action:{approve:'Approved / queued (simulation)',change:'Changes requested',reject:'Rejected'}[action],comment:comment.trim()||'Approved in the client demonstration.',time:new Date().toLocaleString('en-GB'),reviewer:'SUNIL · demo reviewer'});return c;}
function provenance(){if(state.page==='reports'&&hasReportDates()){const selected=reportSnapshot();modal('Report data provenance',selected?table(['Field','Published value'],Object.entries(selected).filter(([k])=>k!=='predictions'&&k!=='failureReason').map(([k,v])=>[esc(k),esc(v)]))+`<p style="margin-top:16px">Latest published snapshot in the selected period. Weekly Churn Summary includes all matching published snapshots. Synthetic demonstration data.</p>`:reportNoData());return;}modal('Data provenance',table(['Field','Published value'],Object.entries(run).filter(([k])=>k!=='predictions'&&k!=='failureReason').map(([k,v])=>[esc(k),esc(v)]), 'class="provenance"')+`<p style="margin-top:16px">Recovered from the published Replit demo. These model and pipeline identifiers are fixture metadata, not evidence of a live connected model.</p><label class="field scenario">Demo scenario<select id="scenario"><option value="published" ${!state.failed?'selected':''}>Published run</option><option value="failed" ${state.failed?'selected':''}>Latest run rejected · fallback</option></select></label>${state.failed?`<div class="fallback">${D.failedRun.scoringRunId}: ${esc(D.failedRun.failureReason)}. Rejected predictions are never shown.</div>`:''}`);}
function legacyMap(){const selected=state.segment==='all'?run.predictions:run.predictions.filter(p=>p.microSegmentId===state.segment);modal('Churn risk map',`<p class="section-sub">Explore the relationships in the published scoring data.</p><label class="field" style="margin:18px 0">Micro-segment<select id="map-segment"><option value="all">All segments</option>${D.segments.map(s=>`<option value="${s.id}" ${state.segment===s.id?'selected':''}>${s.name}</option>`).join('')}</select></label><div class="network"><svg class="network-lines" viewBox="0 0 900 380" preserveAspectRatio="none" aria-hidden="true"><path d="M170 70C310 70 240 180 450 180S600 70 750 70 M170 250C310 250 320 180 450 180S600 260 750 260"/></svg><div class="network-col"><h3>Micro-segments</h3>${D.segments.map(s=>`<div class="network-node ${state.segment===s.id?'chosen':''}">${s.name}</div>`).join('')}</div><div class="network-col"><h3>Signal families</h3>${D.signalGroups.map(s=>`<div class="network-node">${s.name}</div>`).join('')}</div><div class="network-col"><h3>Predicted risk</h3>${['HIGH','MEDIUM','LOW'].map(b=>`<div class="network-node ${b==='HIGH'?'risk-high':''}">${b} · ${selected.filter(p=>p.riskBand===b).length} subscribers</div>`).join('')}</div></div><p class="meta">Lines illustrate the relationship between segments, signal families and model outputs. They do not represent causal attribution.</p>${table(['Primary reason','Signal family','Subscribers'],Object.entries(selected.reduce((a,p)=>(a[p.primaryReason]=(a[p.primaryReason]||0)+1,a),{})).map(([r,n])=>[esc(r),esc(D.signalGroups.find(s=>s.id===D.reasonSignalMap[r])?.name||'Unknown'),n]))}`);}
function pulse(q){if(window.SENTINEL_MART?.active)return;let a;if(state.page==='brief')a=briefAnswer(q);else if(state.page==='reports'&&state.report==='business')a=businessPulse(q);else if(state.page==='reports')a=reportPulseAnswer();else if(state.line!=='Prepaid')a=`${state.line} is not configured in this demo. No data is available.`;else if(/approval|approve|decision/i.test(q))a=`${campaigns.filter(c=>c.status==='pending').length} campaign needs approval. Review its audience, offer, cost and evidence in My Decisions. Approval queues a simulation only; it does not execute the campaign.`;else if(/revenue|model/i.test(q))a='The revenue report uses separate illustrative business figures. COM01 provides predicted churn risk, not revenue or actual churn measurements.';else if(/protected/i.test(q))a=`${protectedCount} unique subscribers have completed retained outcome windows following a tracked intervention, supported by a prior high-risk prediction. This is an observed association, not a causal uplift estimate.`;else if(/reason|why|risk/i.test(q))a=`${high.length} of ${run.predictions.length} scored subscribers are high risk. Recharge lapsing and Usage declining each contain 2 high-risk subscribers. Top recorded reasons include declining data usage, service disruptions and price-plan mismatch.`;else if(/report|show/i.test(q))a=`${reportNames[state.report]} shows ${state.report==='business'?'illustrative weekly revenue, subscriber base, usage and movement figures':'published synthetic churn data or simulated campaign records'}. Downloads contain the displayed table.`;else a='I can explain the demo’s churn risk, protected count, campaign approvals and report data. This sample assistant uses predefined answers; free-form analysis is not connected.';$('#pulse-conversation').innerHTML=`<div class="conversation"><p class="asked">${esc(q)}</p><p>${a}</p><p class="source">Source: ${state.page==='reports'&&state.report==='business'?`Synthetic business data · ${BUSINESS_REPORT.dataAsOf}`:`published demo data · ${state.page==='reports'?(reportSnapshot()?date(reportSnapshot().dataAsOfTs):'no snapshot in selected period'):date(run.dataAsOfTs)}`}</p></div>`;}
function downloadExcel(){downloadReportXlsx();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))$('#detail-dialog').close();if(b.dataset.tab){state.tab=b.dataset.tab;render();}if(b.dataset.review)review(b.dataset.review);if(b.dataset.question)pulse(b.dataset.question);if(b.hasAttribute('data-provenance'))provenance();if(b.hasAttribute('data-map'))map();if(b.hasAttribute('data-print'))window.print();if(b.hasAttribute('data-export'))downloadExcel();if(b.dataset.decision){try{decide(b.dataset.id,b.dataset.decision,$('#review-comment').value);$('#detail-dialog').close();render();$('#notice').textContent='Review recorded in this demo. No live campaign executed.';$('#notice').hidden=false;setTimeout(()=>$('#notice').hidden=true,4500);}catch(err){$('#review-error').textContent=err.message;}}});
document.addEventListener('change',e=>{if(e.target.id==='business-line'){state.line=e.target.value;render();}if(e.target.id==='report-select'){state.report=e.target.value;location.hash='#reports/'+state.report;render();}if(e.target.id==='scenario'){state.failed=e.target.value==='failed';$('#detail-dialog').close();render();provenance();}if(e.target.id==='map-segment'){state.segment=e.target.value;$('#detail-dialog').close();map();}});
$('#pulse-form').addEventListener('submit',e=>{e.preventDefault();const q=$('#pulse-input').value.trim();if(q){pulse(q);$('#pulse-input').value='';}});window.addEventListener('hashchange',render);
window.SentinelDemo={published,run,high,newly,protectedCount,decide,reportData,state,campaigns};
if(document.modelContext?.registerTool){document.modelContext.registerTool({name:'read_sentinel_demo',description:'Read published synthetic churn counts and simulated campaign states. No live backend.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({content:[{type:'text',text:JSON.stringify({synthetic:true,run:run.scoringRunId,high:high.length,scored:run.predictions.length,newly,protected:protectedCount,campaigns})}]})});}
render();

