// Executive Brief follows the supplied Replit screenshots.
const shieldIcon='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 3 20 6v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z" stroke="currentColor" stroke-width="1.8"/><path d="m8.5 11.5 2.5 2.5 4.5-5" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';
const agentIcon='<svg viewBox="0 0 40 44" fill="none" aria-hidden="true"><path d="m20 2 16 9v22l-16 9L4 33V11L20 2Z" stroke="currentColor" stroke-width="1.7"/><rect x="10" y="15" width="20" height="15" rx="4" stroke="currentColor" stroke-width="1.7"/><path d="M20 15V9m-4 0h8" stroke="currentColor" stroke-width="1.7"/><circle cx="16" cy="22" r="1.7" fill="currentColor"/><circle cx="24" cy="22" r="1.7"/></svg>';
function help(text){return `<span class="hint"><button type="button" class="hint-icon" aria-label="${esc(text)}">i</button><span class="hint-pop" role="tooltip">${esc(text)}</span></span>`;}
const briefQuestions=['Why did high-risk subscribers increase?','Which Prepaid segment has the highest risk?','How many subscribers were protected from churn?','What are the key drivers for Recharge Lapsing?','Show the risk trend for the last 3 runs.','What are the top churn reasons?','How many subscribers are at risk?','How many are newly at risk?','What data is this based on?'];
function brief(){return screenshotBrief();}
function map(){return screenshotMap();}
function prepareBriefShell(){
 const isBrief=state.page==='brief';document.body.classList.toggle('brief-page',isBrief);
 $('.pulse-header h2').innerHTML=isBrief?`Ask Pulse ${help(`Ask questions about the currently published COM01 ${state.line} data. Pulse answers only from data available to this governed view.`)}`:'Ask Pulse <span class="info" title="Answers come from the selected demo data, not a generative model.">ⓘ</span>';
 $('.brand-mark').innerHTML=isBrief?shieldIcon:'S';
 const icons={brief:'<rect x="3" y="3" width="6" height="8" rx="1"/><rect x="13" y="3" width="6" height="5" rx="1"/><rect x="3" y="15" width="6" height="5" rx="1"/><rect x="13" y="12" width="6" height="8" rx="1"/>',decisions:'<path d="m3 6 2 2 3-4M12 6h8M3 15l2 2 3-4M12 15h8M12 20h8"/>',reports:'<path d="M5 3h10l4 4v14H5V3Zm10 0v5h4M8 12h8M8 16h8"/>'};
 document.querySelectorAll('[data-page]').forEach(a=>{a.innerHTML=(isBrief?`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">${icons[a.dataset.page]}</svg>`:'')+names[a.dataset.page];});
 $('.send').innerHTML=isBrief?'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="m3 10 18-7-7 18-4-7-7-4Z" stroke-linejoin="round"/><path d="m10 14 11-11"/></svg>':'Send';
 $('.pulse-compose p').textContent=isBrief?`Responses are based on the current published COM01 ${state.line} data.`:'Answers use the selected synthetic data.';
}
function briefToolbar(){return `<div class="toolbar brief-toolbar"><div class="toolbar-left"><label class="field"><span>BUSINESS LINE ${help('Select the business line for the Executive Brief.')}</span><select id="business-line">${['Prepaid','Postpaid','Fibre'].map(v=>`<option ${v===state.line?'selected':''}>${v}</option>`).join('')}</select></label></div><span class="data-date">Data as of <strong>${date(run.dataAsOfTs)}, 04:30 AFT</strong> ${help('Source data cutoff for the current published run. Afghanistan time is UTC+04:30.')}</span></div>`;}
function screenshotBrief(){
 const hour=Number(new Intl.DateTimeFormat('en-GB',{hour:'numeric',hourCycle:'h23',timeZone:'Asia/Kabul'}).format(new Date()));
 const greeting=hour>=5&&hour<12?'morning':hour>=12&&hour<17?'afternoon':'evening';
 const oldHigh=previous.predictions.filter(p=>p.riskBand==='HIGH').length;
 const newScored=run.predictions.filter(p=>!previous.predictions.some(q=>q.serviceInstanceId===p.serviceInstanceId)).length;
 const stats=[['High-risk<br>subscribers',high.length,`+${high.length-oldHigh} (+${((high.length-oldHigh)/oldHigh*100).toFixed(1)}%) vs<br>previous run`,'Prepaid subscribers above the approved High-risk threshold in the current published COM01 run.'],['Newly at risk',newly,`${newScored} new to scoring ${help('New to scoring is shown separately and is not counted as newly at risk.')}`,'Subscribers scored in both runs who moved from Low or Medium to High risk.'],['High-risk share',pct(high.length,run.predictions.length),'of subscribers scored','High-risk subscribers divided by the entire scored population.'],['Subscribers<br>scored',run.predictions.length,'30-day horizon','Unique service instances scored in the current approved and published run.'],['Subscribers<br>protected',protectedCount,'at risk but retained','Previously high-risk subscribers with a completed retained outcome following a tracked intervention. This does not establish causal uplift.']];
 const trend=published.map(r=>r.predictions.filter(p=>p.riskBand==='HIGH').length);
 const reasons=Object.entries(high.reduce((a,p)=>(a[p.primaryReason]=(a[p.primaryReason]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);
 const points=trend.map((n,i)=>`${55+i*300},${226-n*25}`).join(' ');
 const segments=`<div class="table-wrap"><table class="segment-table"><thead><tr><th>SEGMENT</th><th>SUBSCRIBERS</th><th>HIGH RISK</th><th>RISK SHARE ${help('Share of all high-risk subscribers: segment High-risk count divided by 7.')}</th></tr></thead><tbody>${D.segments.map(s=>{const a=run.predictions.filter(p=>p.microSegmentId===s.id),h=a.filter(p=>p.riskBand==='HIGH').length;return `<tr data-segment="${s.id}" class="${state.segment===s.id?'selected':''}"><td><button class="segment-link" data-segment="${s.id}">${s.name}</button></td><td class="num">${a.length}</td><td class="num">${h}</td><td><div class="risk"><div class="track"><div class="fill" style="width:${h/high.length*100}%"></div></div><span>${pct(h,high.length)}</span></div></td></tr>`;}).join('')}</tbody></table></div>`;
 return `<h1>Good ${greeting}, Sunil.</h1><p class="page-sub">Customer retention needs attention.</p>${briefToolbar()}${state.line!=='Prepaid'?empty():`${state.failed?'<div class="fallback">Latest run did not pass publication checks. Showing the last published run from 22 Sep 2026.</div>':''}<div class="kpis">${stats.map(([label,value,caption,tip])=>`<div class="kpi"><div class="label"><span>${label}</span>${help(tip)}</div><div class="value">${value}</div><div class="caption">${caption}</div></div>`).join('')}</div><section class="section"><div class="section-heading"><div><h2>Churn trend ${help('High-risk subscriber counts across approved and published scoring runs.')}</h2><p class="section-sub">High-risk subscribers (Prepaid) · Approved runs only</p></div></div><div class="panel chart-panel"><svg class="trend" viewBox="0 0 990 275" role="img" aria-label="High-risk subscribers: 4 on 1 September, 5 on 8 September, 4 on 15 September, 7 on 22 September">${[0,2,4,6,8].map(n=>`<path class="grid" d="M55 ${226-n*25}H955"/><text x="46" y="${231-n*25}" text-anchor="end">${n}</text>`).join('')}<polyline class="line" points="${points}"/>${trend.map((n,i)=>`<circle class="dot" cx="${55+i*300}" cy="${226-n*25}" r="3.7"><title>${date(published[i].dataAsOfTs)}: ${n} high-risk subscribers</title></circle><text x="${55+i*300}" y="247" text-anchor="middle">${String(1+i*7).padStart(2,'0')} Sept</text>`).join('')}</svg></div></section><section class="section"><div class="section-heading"><div><h2>Risk by prepaid segment ${help('Prepaid micro-segments from the current published run.')}</h2><p class="section-sub">Select a segment to focus the Churn Agent</p></div></div><div class="panel">${segments}</div></section><section class="panel churn-launch"><div><h2>Churn Map ${help('Explore how primary explanation groups connect through segments to predicted risk. These are not causal paths.')}</h2><p class="section-sub">Explore signals, prepaid segments and risk outcomes.</p></div><button class="agent-launch" data-map><span class="agent-tile">${agentIcon}</span><span>Churn Agent</span></button></section><section class="section"><div class="section-heading"><div><h2>Top churn reasons ${help('Primary reasons among the 7 high-risk subscribers in this published run.')}</h2><p class="section-sub">High-risk subscribers (Prepaid)</p></div></div><div class="panel reason-list">${reasons.map(([name,n])=>`<div class="reason"><span>${esc(name)}</span><div class="bar"><span style="width:${n/high.length*100}%"></span></div><strong>${n}</strong></div>`).join('')}</div></section>`}<footer class="footer brief-footer"><span>COM01 · ${run.scoringRunId} · 30-day horizon</span><span><button class="link-button" data-provenance>View provenance</button> ${help('Model version, pipeline, thresholds and publication status for this run.')}</span></footer>`;
}
let mapSelection=null;
const graphGeom={signal:{x:0,w:220},segment:{x:350,w:220},model:{x:680,w:166},risk:{x:935,w:165}};
const nodeY=i=>45+i*78;
const riskY={HIGH:84,MEDIUM:240,LOW:396};
const signalOf=p=>D.reasonSignalMap[p.primaryReason];
function flowCounts(preds){const sigSeg=new Map(),segModel=new Map(),risk=new Map();for(const p of preds){segModel.set(p.microSegmentId,(segModel.get(p.microSegmentId)||0)+1);risk.set(p.riskBand,(risk.get(p.riskBand)||0)+1);if(p.riskBand==='HIGH'){const key=signalOf(p)+'|'+p.microSegmentId;sigSeg.set(key,(sigSeg.get(key)||0)+1);}}return {sigSeg,segModel,risk};}
function selectedPredictions(){if(!mapSelection)return run.predictions;const {kind,id}=mapSelection;return run.predictions.filter(p=>kind==='signal'?p.riskBand==='HIGH'&&signalOf(p)===id:kind==='segment'?p.microSegmentId===id:kind==='risk'?p.riskBand===id:true);}
function flowPath(x1,y1,x2,y2){const mid=(x1+x2)/2;return `M${x1} ${y1}C${mid} ${y1},${mid} ${y2},${x2} ${y2}`;}
function graphEdges(){const all=flowCounts(run.predictions),active=flowCounts(selectedPredictions());let paths=[];
 function edge(key,n,isActive,x1,y1,x2,y2,color){const d=flowPath(x1,y1,x2,y2);paths.push(`<path d="${d}" class="flow-band ${mapSelection&&!isActive?'dim':''}" stroke="${color}" stroke-width="${7+n*2}"/><path d="${d}" class="flow-tracer ${mapSelection&&!isActive?'dim':''}" stroke="${color}"/>`);}
 for(const [key,n] of all.sigSeg){const [sig,seg]=key.split('|');edge(key,n,active.sigSeg.has(key),220,nodeY(D.signalGroups.findIndex(s=>s.id===sig))+28,350,nodeY(D.segments.findIndex(s=>s.id===seg))+28,'#3985db');}
 for(const [id,n] of all.segModel)edge(id,n,active.segModel.has(id),570,nodeY(D.segments.findIndex(s=>s.id===id))+28,680,267,'#3985db');
 for(const [id,n] of all.risk)edge(id,n,active.risk.has(id),846,267,935,riskY[id]+28,{HIGH:'#e55e62',MEDIUM:'#569aee',LOW:'#a1adbc'}[id]);return paths.join('');
}
function graphNode(kind,id,label,value,y,x,w,bar,color){const preds=selectedPredictions();let active=!mapSelection||kind==='model'||preds.some(p=>kind==='signal'?p.riskBand==='HIGH'&&signalOf(p)===id:kind==='segment'?p.microSegmentId===id:p.riskBand===id);const chosen=mapSelection?.kind===kind&&mapSelection.id===id;return `<button class="flow-node ${kind==='model'?'model-node':''} ${!active?'dim':''} ${chosen?'chosen':''}" data-node-kind="${kind}" data-node-id="${id}" aria-pressed="${chosen}" style="left:${x/11}%;top:${y}px;width:${w/11}%">${kind==='model'?`<span class="model-icon">${agentIcon}</span><strong>Churn model</strong><small>${run.modelVersion}</small><small>Model family unavailable</small>`:`<span class="node-line"><span>${label}</span><strong>${value}</strong></span><span class="node-bar"><span style="width:${bar}%;background:${color}"></span></span>`}</button>`;}
function detailMetric(label,value){return `<div><span>${label}</span><strong>${value}</strong></div>`;}
function modelDetails(){return `<p class="detail-eyebrow">CHURN MODEL</p><h3>Approved champion</h3><dl class="model-meta">${[['Model version',run.modelVersion],['Model family','Not available in governed metadata'],['Prediction horizon','30 days'],['Segmentation','COM01-PREPAID-SEG-v1'],['Threshold policy',`${run.thresholdPolicyId} · ${run.thresholdPolicyVersion}`]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="detail-metrics">${detailMetric('Subscribers scored',run.predictions.length)}${detailMetric('High risk',high.length)}</div><p class="detail-note">Select a segment to see its population, High-risk concentration and defining characteristics.</p>`;}
function selectionDetails(){if(!mapSelection||mapSelection.kind==='model')return modelDetails();const {kind,id}=mapSelection,preds=selectedPredictions();if(kind==='signal'){const sig=D.signalGroups.find(s=>s.id===id);const groups=D.segments.map(s=>({s,n:preds.filter(p=>p.microSegmentId===s.id).length})).filter(g=>g.n);return `<p class="detail-eyebrow">KEY SIGNAL</p><h3>${sig.name}</h3><div class="detail-metrics">${detailMetric('Share of High-risk explanations',pct(preds.length,high.length))}${detailMetric('High-risk subscribers',preds.length)}</div><p class="detail-eyebrow">SEGMENTS MOST ASSOCIATED</p>${groups.map(g=>`<div class="detail-association"><span>${g.s.name}</span><strong>${g.n} · ${pct(g.n,preds.length)}</strong><div class="node-bar"><span style="width:${g.n/preds.length*100}%;background:#3997ff"></span></div></div>`).join('')||'<p class="detail-note">No primary high-risk explanations in this signal group.</p>'}<p class="detail-note">Counted by primary explanation group. Not SHAP or model importance.</p>`;}
if(kind==='segment'){const s=D.segments.find(s=>s.id===id),h=preds.filter(p=>p.riskBand==='HIGH');return `<p class="detail-eyebrow">PREPAID SEGMENT</p><h3>${s.name}</h3><div class="detail-metrics">${detailMetric('Subscribers scored',preds.length)}${detailMetric('High-risk subscribers',h.length)}</div><p class="detail-eyebrow">DEFINING CHARACTERISTICS</p>${s.characteristics.map(c=>`<p class="detail-note">${esc(c)}</p>`).join('')}<p class="detail-eyebrow">PRIMARY HIGH-RISK REASONS</p>${Object.entries(h.reduce((a,p)=>(a[p.primaryReason]=(a[p.primaryReason]||0)+1,a),{})).map(([r,n])=>`<div class="detail-association"><span>${r}</span><strong>${n}</strong></div>`).join('')||'<p class="detail-note">No high-risk subscribers in this segment.</p>'}`;}
return `<p class="detail-eyebrow">RISK OUTCOME</p><h3>${id[0]+id.slice(1).toLowerCase()} risk</h3><div class="detail-metrics">${detailMetric('Subscribers',preds.length)}${detailMetric('Share of scored',pct(preds.length,run.predictions.length))}</div><p class="detail-eyebrow">SEGMENT DISTRIBUTION</p>${D.segments.map(s=>[s,preds.filter(p=>p.microSegmentId===s.id).length]).filter(([,n])=>n).map(([s,n])=>`<div class="detail-association"><span>${s.name}</span><strong>${n}</strong></div>`).join('')}<p class="detail-note">Risk is predicted over 30 days and is not observed churn.</p>`;}
function graphMarkup(){return `<div class="flow-instruction"><span>Select any signal, segment or risk outcome to trace its path.</span>${mapSelection?'<button data-clear-map>Clear selection</button>':''}</div><div class="flow-scroll"><div class="flow-canvas"><div class="flow-headings">${[['01','KEY SIGNALS','Share of High-risk explanations · n=7'],['02','PREPAID SEGMENTS','All scored · n=13'],['03','CHURN MODEL','Approved champion'],['04','RISK OUTCOME','All scored · n=13']].map(([i,l,c])=>`<div><h3><span>${i}</span> ${l} ${help(c)}</h3><p>${c}</p></div>`).join('')}</div><div class="flow-graph"><svg viewBox="0 0 1100 550" preserveAspectRatio="none" aria-hidden="true">${graphEdges()}</svg>${D.signalGroups.map((s,i)=>{const n=high.filter(p=>signalOf(p)===s.id).length;return graphNode('signal',s.id,s.name,pct(n,high.length),nodeY(i),0,220,n/high.length*100,'#3997ff');}).join('')}${D.segments.map((s,i)=>{const a=run.predictions.filter(p=>p.microSegmentId===s.id),h=a.filter(p=>p.riskBand==='HIGH').length;return graphNode('segment',s.id,s.name,a.length,nodeY(i),350,220,h/run.predictions.length*100,'#e96363');}).join('')}${graphNode('model','champion','',0,190,680,166,0,'')}${['HIGH','MEDIUM','LOW'].map(id=>{const n=run.predictions.filter(p=>p.riskBand===id).length;return graphNode('risk',id,id[0]+id.slice(1).toLowerCase()+' risk',n,riskY[id],935,165,n/run.predictions.length*100,{HIGH:'#e96363',MEDIUM:'#579bef',LOW:'#a1adbc'}[id]);}).join('')}</div></div></div><p class="flow-footnote">Line widths are subscriber counts from the served run. Signals → segments count High-risk subscribers by primary explanation group (n=7); segments → model → outcome count all scored Prepaid subscribers (n=13). Not SHAP values or causal importance.</p>`;}
function screenshotMap(){if(state.segment!=='all'&&!mapSelection)mapSelection={kind:'segment',id:state.segment};const dialog=$('#detail-dialog');dialog.classList.add('churn-dialog');$('#dialog-title').innerHTML=`<span class="dialog-agent-icon">${agentIcon}</span><span>Churn Agent ${help('Published synthetic COM01 scoring relationships.')}<small>Interactive view of how signals flow through segments to predict churn risk (${state.line})</small><em>${run.scoringRunId} <span>Data as of ${date(run.dataAsOfTs)}, 04:30 AFT</span></em></span>`;$('#dialog-content').innerHTML=`<div class="churn-dialog-layout"><div class="flow-main">${graphMarkup()}</div><aside class="flow-details">${selectionDetails()}</aside></div>`;if(!dialog.open)dialog.showModal();}
function briefAnswer(q){if(state.line!=='Prepaid')return `${state.line} has no configured data in this demonstration.`;if(/increase/i.test(q))return 'High-risk subscribers increased from 4 to 7 (+75.0%). Two existing subscribers moved into High risk and one High-risk subscriber is new to scoring.';if(/highest|concentrated/i.test(q))return 'Recharge lapsing and Usage declining each have 2 High-risk subscribers, representing 28.6% each of all High-risk subscribers. Each segment contains 2 scored subscribers.';if(/protected/i.test(q))return '2 previously at-risk subscribers have completed retained outcome windows following tracked interventions. This is an observed association, not an estimate of causal retention uplift.';if(/recharge|drivers/i.test(q))return 'Recharge lapsing has 2 High-risk subscribers. Their primary reasons are Contract nearing expiry and Price-plan mismatch, one subscriber each. These are synthetic fixture labels.';if(/trend|runs/i.test(q))return 'The last 3 published runs contain 5 High-risk subscribers on 8 Sep, 4 on 15 Sep and 7 on 22 Sep 2026.';if(/top|reasons/i.test(q))return 'Declining data usage, Repeated service disruptions and Price-plan mismatch each explain 2 High-risk subscribers. Contract nearing expiry explains 1.';if(/newly/i.test(q))return '2 subscribers moved from a non-High band into High risk compared with the previous published run. 1 additional subscriber is new to scoring and is reported separately.';if(/at risk/i.test(q))return '7 of the 13 scored Prepaid subscribers are High risk, a share of 53.8%, over a 30-day prediction horizon.';if(/data|based|published/i.test(q))return `This view uses ${run.scoringRunId}, approved and published, with data as of 22 Sep 2026, 04:30 AFT. All data is synthetic. Rejected runs are excluded.`;return 'I can answer questions about the published COM01 risk, segments, reasons, trend and protected count. This demo uses predefined answers.';}
document.addEventListener('click',e=>{
 const segment=e.target.closest('[data-segment]');if(segment&&state.page==='brief'){state.segment=segment.dataset.segment;mapSelection={kind:'segment',id:state.segment};screenshotMap();}
 const node=e.target.closest('[data-node-kind]');if(node){mapSelection={kind:node.dataset.nodeKind,id:node.dataset.nodeId};screenshotMap();const next=document.querySelector(`[data-node-kind="${node.dataset.nodeKind}"][data-node-id="${node.dataset.nodeId}"]`);next?.focus();}
 if(e.target.closest('[data-clear-map]')){mapSelection=null;state.segment='all';screenshotMap();}
});
