// Standalone BI fixture and arithmetic. No prediction or model metadata is used.
const BUSINESS_REPORT={
 id:'BI-WEEKLY-20260927',businessLine:'Prepaid',dataAsOf:'27 Sep 2026, 23:59 AFT',
 weekLabels:['Week 36','Week 37','Week 38','Week 39'],weekDates:['31 Aug–06 Sep','07–13 Sep','14–20 Sep','21–27 Sep'],
 trendLabel:'12-week trend · Weeks 28–39',monthLabel:'01–27 Sep vs 01–27 Aug',
 sources:[['Revenue','Billing / recharge transactions','Sum of recorded service revenue by week.'],['Base','Subscriber status snapshots','Distinct active service instances at week end. Voice and data users may overlap.'],['Usage','Rated voice and data usage','Usage per active user, calculated from usage totals and eligible active users.'],['Movement','Activation / termination events','Gross additions, observed churn and net additions from recorded events.']],
 metrics:[
 {group:'Revenue',name:'Service revenue',unit:'USD',values:[10820,11260,11040,11680],month:[44200,42000],decimals:0},
 {group:'Revenue',name:'Recharge revenue',unit:'USD',values:[7840,8060,7990,8470],month:[32400,30800],decimals:0},
 {group:'Revenue',name:'Data revenue',unit:'USD',values:[2980,3200,3050,3210],month:[11800,11200],decimals:0},
 {group:'Base',name:'Active subscribers',unit:'subscribers',values:[18420,18580,18720,18860],month:[18860,18200],snapshot:true,decimals:0},
 {group:'Base',name:'Voice active users',unit:'subscribers',values:[12200,12310,12400,12540],month:[12540,12100],snapshot:true,decimals:0},
 {group:'Base',name:'Data active users',unit:'subscribers',values:[16500,16630,16800,17020],month:[17020,16100],snapshot:true,decimals:0},
 {group:'Usage',name:'Voice minutes per user',unit:'minutes',values:[4.8,5.0,5.2,5.1],month:[5.0,4.7],decimals:1},
 {group:'Usage',name:'Data usage per user',unit:'MB',values:[1019,1057,1078,1095],month:[1065,1010],decimals:0},
 {group:'Movement',name:'Gross additions',unit:'subscribers',values:[410,430,405,460],month:[1650,1600],decimals:0},
 {group:'Movement',name:'Actual churn',unit:'subscribers',values:[235,228,241,216],month:[880,960],decimals:0,lowerBetter:true},
 {group:'Movement',name:'Net additions',unit:'subscribers',values:[175,202,164,244],month:[770,640],decimals:0}
 ]
};
const biChange=(current,prior)=>prior===0?null:(current-prior)/Math.abs(prior)*100;
const biNumber=(n,decimals=0)=>n.toLocaleString('en-GB',{minimumFractionDigits:decimals,maximumFractionDigits:decimals});
const biPercent=n=>n===null?'—':`${n>0?'+':''}${n.toFixed(1)}%`;
function biTrend(m){return [...[.91,.93,.95,.97,.94,.99,.97,.985].map(f=>Number((m.values[0]*f).toFixed(m.decimals))),...m.values];}
function biWeekIndices(){return BUSINESS_REPORT.weekLabels.map((_,i)=>i).filter(i=>overlapsReportDates(['2026-08-31','2026-09-07','2026-09-14','2026-09-21'][i],['2026-09-06','2026-09-13','2026-09-20','2026-09-27'][i]));}
function biLatestIndex(){return biWeekIndices().at(-1);}
function biWeekChange(m){const i=biLatestIndex();return i>0?biChange(m.values[i],m.values[i-1]):null;}
function biVisibleTrend(m){return hasReportDates()?biWeekIndices().map(i=>m.values[i]):biTrend(m);}
function biTrendLabel(){return hasReportDates()?'Selected weekly trend':BUSINESS_REPORT.trendLabel;}
function biPeriodLabel(){const indices=biWeekIndices();if(!indices.length)return '';if(!hasReportDates())return 'Week 39 · 21–27 September 2026';return indices.map(i=>`${BUSINESS_REPORT.weekLabels[i]} · ${BUSINESS_REPORT.weekDates[i]} 2026`).join(' / ');}
function biExportData(){const indices=biWeekIndices();return {headers:['Category','Metric','Unit',...indices.map(i=>hasReportDates()?`${BUSINESS_REPORT.weekLabels[i]} · ${BUSINESS_REPORT.weekDates[i]} 2026`:BUSINESS_REPORT.weekLabels[i]),'WoW','MoM',biTrendLabel(),'MoM basis'],rows:indices.length?BUSINESS_REPORT.metrics.map(m=>[m.group,m.name,m.unit,...indices.map(i=>biNumber(m.values[i],m.decimals)),biPercent(biWeekChange(m)),hasReportDates()?'Not available':biPercent(biChange(...m.month)),biVisibleTrend(m).join(', '),hasReportDates()?'Unavailable for a custom weekly range':m.snapshot?'27 Sep vs 31 Aug snapshot':BUSINESS_REPORT.monthLabel]):[]};}
function biSpark(m){const values=biVisibleTrend(m),min=Math.min(...values),range=Math.max(...values)-min||1;const pts=values.map((v,i)=>`${values.length===1?65:4+i*121/(values.length-1)},${30-(v-min)/range*25}`);const last=pts.at(-1).split(',');return `<svg class="bi-spark" viewBox="0 0 130 36" role="img" aria-label="${esc(m.name)}: ${esc(biTrendLabel())}"><title>${values.map(v=>biNumber(v,m.decimals)).join(', ')}</title><path d="M${pts.join('L')}"/><circle cx="${last[0]}" cy="${last[1]}" r="2"/></svg>`;}
function biDelta(m,type){const n=type==='week'?biWeekChange(m):hasReportDates()?null:biChange(...m.month);const good=n!==null&&(m.lowerBetter?n<0:n>0);const neutral=n===null||Math.abs(n)<.05;return `<span class="bi-delta ${neutral?'neutral':good?'good':'bad'}"><span aria-hidden="true">${neutral?'':n>0?'↑':'↓'}</span> ${biPercent(n)}</span>`;}
function biReportTable(){const indices=biWeekIndices();let rows='';for(const group of ['Revenue','Base','Usage','Movement']){const metrics=BUSINESS_REPORT.metrics.filter(m=>m.group===group);metrics.forEach((m,i)=>{rows+=`<tr>${i===0?`<th scope="rowgroup" class="bi-group" rowspan="${metrics.length}">${group}</th>`:''}<th scope="row" class="bi-metric">${m.name}<small>${m.unit}</small></th>${indices.map(i=>`<td class="num">${biNumber(m.values[i],m.decimals)}</td>`).join('')}<td class="num">${biDelta(m,'week')}</td><td class="num">${biDelta(m,'month')}</td><td>${biSpark(m)}</td></tr>`;});}return `<div class="table-wrap bi-table-wrap"><table class="bi-table"><thead><tr><th aria-label="Category"></th><th>METRIC</th>${indices.map(i=>`<th class="num">${BUSINESS_REPORT.weekLabels[i]}<small>${BUSINESS_REPORT.weekDates[i]}${hasReportDates()?' 2026':''}</small></th>`).join('')}<th class="num">WoW ${help('Latest displayed week compared with its previous calendar week, even when that prior week is outside the selected range. Unavailable where no prior week is in the sample.')}</th><th class="num">MoM ${help(hasReportDates()?'MoM is unavailable for custom weekly ranges. Clear dates to see the original month-to-date comparison.':'Flow and usage metrics compare 01–27 Sep with 01–27 Aug. Active user metrics compare the latest snapshot with 31 Aug.')}</th><th>${hasReportDates()?'WEEKLY TREND':'12-WEEK TREND'}</th></tr></thead><tbody>${rows}</tbody></table></div>`;}
function biCommentary(){const i=biLatestIndex();if(i===undefined)return [];const m=BUSINESS_REPORT.metrics,revenue=m.find(x=>x.name==='Service revenue'),data=m.find(x=>x.name==='Data revenue'),churn=m.find(x=>x.name==='Actual churn'),net=m.find(x=>x.name==='Net additions');if(i===0)return [{title:'Revenue',text:`Service revenue was USD ${biNumber(revenue.values[i])} in Week 36. The preceding week is unavailable for a WoW comparison.`},{title:'Base & usage',text:`Active subscribers reached ${biNumber(m.find(x=>x.name==='Active subscribers').values[i])}. Data revenue was USD ${biNumber(data.values[i])}.`},{title:'Subscriber movement',text:`Observed churn was ${churn.values[i]}; net additions were ${net.values[i]}. This is recorded movement, separate from predicted churn risk.`}];return [{title:'Revenue',text:`Service revenue ${biWeekChange(revenue)>=0?'rose':'fell'} ${biPercent(biWeekChange(revenue))} WoW to USD ${biNumber(revenue.values[i])}.${!hasReportDates()?' Recharge and data revenue both increased.':''}`},{title:'Base & usage',text:`Active subscribers reached ${biNumber(m.find(x=>x.name==='Active subscribers').values[i])}. Data revenue ${biWeekChange(data)>=0?'rose':'fell'} ${biPercent(biWeekChange(data))} WoW.${!hasReportDates()?' Data usage per user also increased.':''}`},{title:'Subscriber movement',text:`Observed churn ${churn.values[i]<=churn.values[i-1]?'fell':'rose'} from ${churn.values[i-1]} to ${churn.values[i]}. Net additions changed from ${net.values[i-1]} to ${net.values[i]}. This is recorded movement, separate from predicted churn risk.`}];}
function businessReport(){const indices=biWeekIndices(),selects=`<label class="field">Report<select id="report-select">${Object.entries(reportNames).map(([k,v])=>`<option value="${k}" ${state.report===k?'selected':''}>${v}</option>`).join('')}</select></label>`;return `<h1>Reports</h1><p class="page-sub">Business performance from operational data.</p><div class="toolbar"><div class="toolbar-left"><label class="field">Business line<select id="business-line">${['Prepaid','Postpaid','Fibre'].map(v=>`<option ${v===state.line?'selected':''}>${v}</option>`).join('')}</select></label>${selects}</div><span class="data-date">Data as of ${BUSINESS_REPORT.dataAsOf}</span></div>${reportDateControls()}${reportRangeNote()}${state.line!==BUSINESS_REPORT.businessLine?empty():!indices.length?reportNoData():`<section class="bi-report"><div class="report-title"><div><span class="bi-eyebrow">ATOMA · PREPAID</span><h2>Weekly Business Performance</h2><p>${biPeriodLabel()}</p></div><div class="actions"><button class="button" data-export>Download Excel (.xlsx)</button><button class="button" data-print>Print / Save PDF</button></div></div><p class="bi-headline">${hasReportDates()?`Commentary covers the latest displayed week: ${BUSINESS_REPORT.weekLabels[biLatestIndex()]}.`:'Revenue growth and lower observed churn strengthen weekly performance.'}</p><div class="bi-data-line"><span>Operational data · Calculated KPIs</span><span>Synthetic sample ${help('This demonstration uses standalone business data and arithmetic. No ML scores, prediction runs or model outputs feed this report.')}</span></div><div class="bi-report-grid"><div class="panel">${biReportTable()}</div><aside class="bi-commentary" aria-label="Business commentary">${biCommentary().map(c=>`<section><h3>${c.title}</h3><p>${c.text}</p></section>`).join('')}</aside></div><p class="bi-footnote">${hasReportDates()?'Full overlapping weeks are shown. WoW compares the latest displayed week with its previous calendar week. MoM is unavailable for this custom range. Trends use displayed weeks only.':'WoW: current vs previous week. MoM: equivalent month-to-date periods; active user counts compare with the previous month end. Trends show 12 sample weeks.'}</p></section>`}<footer class="footer"><span>Business data · ${BUSINESS_REPORT.id}</span><button class="link-button" data-business-source>View data sources</button><span>Synthetic demonstration</span></footer>`;}
function businessSources(){modal('Business report data sources',`<p>This report uses a standalone synthetic business dataset and arithmetic aggregation. It has no dependency on COM01 predictions or a trained model.</p>${table(['Metric group','Source type','Calculation'],BUSINESS_REPORT.sources.map(row=>row.map(esc)))}<dl class="detail-list">${[['Report snapshot',BUSINESS_REPORT.id],['Data as of',BUSINESS_REPORT.dataAsOf],['WoW','Latest displayed week compared with its previous calendar week; unavailable without prior sample data.'],['MoM',hasReportDates()?'Unavailable for a custom weekly range.':'Same-day MTD comparison; active user metrics use the prior month-end snapshot.'],['Net additions','Recorded gross additions minus observed churn.'],['Commentary','Template text derived from the displayed sample values.']].map(([k,v])=>`<div class="detail-row"><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><p style="margin-top:18px">Live source connectors and data lake storage are not connected in this prototype.</p>`);}
function businessPulse(q){if(state.line!==BUSINESS_REPORT.businessLine)return `No business data has been configured for ${state.line}.`;if(/ML|AI|model|predict/i.test(q))return 'This report uses operational records and arithmetic KPI calculations. No trained model or prediction output is required. The prototype uses standalone synthetic business data.';if(/source|data/i.test(q))return 'Revenue comes from billing and recharge records; base from subscriber snapshots; usage from rated usage; movement from activation and termination events. These are sample source types, with synthetic figures in this demo.';if(!biWeekIndices().length)return 'No business data is available for the selected period. Choose another range or clear dates.';if(/churn|movement/i.test(q))return biCommentary()[2].text;if(/revenue|week|change/i.test(q))return biCommentary()[0].text;return 'Weekly Business Performance shows the displayed weeks of revenue, subscriber base, usage and movement, with WoW, MoM and 12-week trends. All metrics use the report’s own business data.';}
document.addEventListener('click',e=>{if(e.target.closest('[data-business-source]'))businessSources();});
