window.SENTINEL_DATA = {
  "segments": [
    {
      "id": "recharge-lapsing",
      "name": "Recharge lapsing",
      "version": "COM01-PREPAID-SEG-v1",
      "characteristics": [
        "Longer gaps between recharges",
        "Declining recharge frequency"
      ]
    },
    {
      "id": "usage-declining",
      "name": "Usage declining",
      "version": "COM01-PREPAID-SEG-v1",
      "characteristics": [
        "Declining data usage",
        "Reduced recent activity"
      ]
    },
    {
      "id": "low-engagement",
      "name": "Low engagement",
      "version": "COM01-PREPAID-SEG-v1",
      "characteristics": [
        "Reduced service engagement",
        "Infrequent recent interactions"
      ]
    },
    {
      "id": "new-subscribers",
      "name": "New subscribers",
      "version": "COM01-PREPAID-SEG-v1",
      "characteristics": [
        "Recently activated service",
        "Short observed usage history"
      ]
    },
    {
      "id": "high-value-active",
      "name": "High-value active",
      "version": "COM01-PREPAID-SEG-v1",
      "characteristics": [
        "Active service use",
        "Higher recent engagement"
      ]
    },
    {
      "id": "others",
      "name": "Others",
      "version": "COM01-PREPAID-SEG-v1",
      "characteristics": [
        "Does not meet another segment definition"
      ]
    }
  ],
  "signalGroups": [
    {
      "id": "recharge",
      "name": "Recharge behaviour"
    },
    {
      "id": "usage",
      "name": "Usage decline"
    },
    {
      "id": "balance",
      "name": "Balance pattern"
    },
    {
      "id": "engagement",
      "name": "Engagement"
    },
    {
      "id": "network",
      "name": "Network experience"
    },
    {
      "id": "device-plan",
      "name": "Device & plan behaviour"
    }
  ],
  "reasonSignalMap": {
    "Contract nearing expiry": "device-plan",
    "Declining data usage": "usage",
    "Repeated service disruptions": "network",
    "Price-plan mismatch": "balance"
  },
  "runs": [
    {
      "businessLine": "Prepaid",
      "scoringRunId": "COM01-20260901-01",
      "scoredAtTs": "2026-09-01T01:20:00Z",
      "dataAsOfTs": "2026-09-01T00:00:00Z",
      "predictionHorizonDays": 30,
      "modelVersion": "com01-churn-v2.4",
      "pipelineVersion": "com01-gold-v1.8",
      "thresholdPolicyId": "COM01-RISK-BANDS",
      "thresholdPolicyVersion": "v3",
      "churnDefinitionId": "COM01-30D-CHURN-v2",
      "qualityGateStatus": "PASS",
      "runStatus": "PUBLISHED",
      "failureReason": null,
      "predictions": [
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10004287",
          "churnProbability": 0.86,
          "calibratedChurnProbability": 0.86,
          "riskBand": "HIGH",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10001734",
          "churnProbability": 0.79,
          "calibratedChurnProbability": 0.79,
          "riskBand": "HIGH",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10006519",
          "churnProbability": 0.76,
          "calibratedChurnProbability": 0.76,
          "riskBand": "HIGH",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10002461",
          "churnProbability": 0.74,
          "calibratedChurnProbability": 0.74,
          "riskBand": "HIGH",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10008730",
          "churnProbability": 0.55,
          "calibratedChurnProbability": 0.55,
          "riskBand": "MEDIUM",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10003902",
          "churnProbability": 0.43,
          "calibratedChurnProbability": 0.43,
          "riskBand": "MEDIUM",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10005648",
          "churnProbability": 0.38,
          "calibratedChurnProbability": 0.38,
          "riskBand": "LOW",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10007315",
          "churnProbability": 0.23,
          "calibratedChurnProbability": 0.23,
          "riskBand": "LOW",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10009184",
          "churnProbability": 0.26,
          "calibratedChurnProbability": 0.26,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10001109",
          "churnProbability": 0.31,
          "calibratedChurnProbability": 0.31,
          "riskBand": "LOW",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10008462",
          "churnProbability": 0.37,
          "calibratedChurnProbability": 0.37,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260901-01",
          "serviceInstanceId": "SVC-10002856",
          "churnProbability": 0.29,
          "calibratedChurnProbability": 0.29,
          "riskBand": "LOW",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-01T00:00:00Z"
        }
      ]
    },
    {
      "businessLine": "Prepaid",
      "scoringRunId": "COM01-20260908-01",
      "scoredAtTs": "2026-09-08T01:20:00Z",
      "dataAsOfTs": "2026-09-08T00:00:00Z",
      "predictionHorizonDays": 30,
      "modelVersion": "com01-churn-v2.4",
      "pipelineVersion": "com01-gold-v1.8",
      "thresholdPolicyId": "COM01-RISK-BANDS",
      "thresholdPolicyVersion": "v3",
      "churnDefinitionId": "COM01-30D-CHURN-v2",
      "qualityGateStatus": "PASS",
      "runStatus": "PUBLISHED",
      "failureReason": null,
      "predictions": [
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10004287",
          "churnProbability": 0.88,
          "calibratedChurnProbability": 0.88,
          "riskBand": "HIGH",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10001734",
          "churnProbability": 0.82,
          "calibratedChurnProbability": 0.82,
          "riskBand": "HIGH",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10006519",
          "churnProbability": 0.77,
          "calibratedChurnProbability": 0.77,
          "riskBand": "HIGH",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10002461",
          "churnProbability": 0.75,
          "calibratedChurnProbability": 0.75,
          "riskBand": "HIGH",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10008730",
          "churnProbability": 0.74,
          "calibratedChurnProbability": 0.74,
          "riskBand": "HIGH",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10003902",
          "churnProbability": 0.48,
          "calibratedChurnProbability": 0.48,
          "riskBand": "MEDIUM",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10005648",
          "churnProbability": 0.39,
          "calibratedChurnProbability": 0.39,
          "riskBand": "LOW",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10007315",
          "churnProbability": 0.21,
          "calibratedChurnProbability": 0.21,
          "riskBand": "LOW",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10009184",
          "churnProbability": 0.27,
          "calibratedChurnProbability": 0.27,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10001109",
          "churnProbability": 0.34,
          "calibratedChurnProbability": 0.34,
          "riskBand": "LOW",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10008462",
          "churnProbability": 0.35,
          "calibratedChurnProbability": 0.35,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260908-01",
          "serviceInstanceId": "SVC-10002856",
          "churnProbability": 0.3,
          "calibratedChurnProbability": 0.3,
          "riskBand": "LOW",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-08T00:00:00Z"
        }
      ]
    },
    {
      "businessLine": "Prepaid",
      "scoringRunId": "COM01-20260915-01",
      "scoredAtTs": "2026-09-15T01:20:00Z",
      "dataAsOfTs": "2026-09-15T00:00:00Z",
      "predictionHorizonDays": 30,
      "modelVersion": "com01-churn-v2.4",
      "pipelineVersion": "com01-gold-v1.8",
      "thresholdPolicyId": "COM01-RISK-BANDS",
      "thresholdPolicyVersion": "v3",
      "churnDefinitionId": "COM01-30D-CHURN-v2",
      "qualityGateStatus": "PASS",
      "runStatus": "PUBLISHED",
      "failureReason": null,
      "predictions": [
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10004287",
          "churnProbability": 0.84,
          "calibratedChurnProbability": 0.84,
          "riskBand": "HIGH",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10001734",
          "churnProbability": 0.8,
          "calibratedChurnProbability": 0.8,
          "riskBand": "HIGH",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10006519",
          "churnProbability": 0.78,
          "calibratedChurnProbability": 0.78,
          "riskBand": "HIGH",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10002461",
          "churnProbability": 0.72,
          "calibratedChurnProbability": 0.72,
          "riskBand": "HIGH",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10008730",
          "churnProbability": 0.58,
          "calibratedChurnProbability": 0.58,
          "riskBand": "MEDIUM",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10003902",
          "churnProbability": 0.51,
          "calibratedChurnProbability": 0.51,
          "riskBand": "MEDIUM",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10005648",
          "churnProbability": 0.4,
          "calibratedChurnProbability": 0.4,
          "riskBand": "LOW",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10007315",
          "churnProbability": 0.23,
          "calibratedChurnProbability": 0.23,
          "riskBand": "LOW",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10009184",
          "churnProbability": 0.28,
          "calibratedChurnProbability": 0.28,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10001109",
          "churnProbability": 0.31,
          "calibratedChurnProbability": 0.31,
          "riskBand": "LOW",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10008462",
          "churnProbability": 0.33,
          "calibratedChurnProbability": 0.33,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260915-01",
          "serviceInstanceId": "SVC-10002856",
          "churnProbability": 0.3,
          "calibratedChurnProbability": 0.3,
          "riskBand": "LOW",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-15T00:00:00Z"
        }
      ]
    },
    {
      "businessLine": "Prepaid",
      "scoringRunId": "COM01-20260922-01",
      "scoredAtTs": "2026-09-22T01:20:00Z",
      "dataAsOfTs": "2026-09-22T00:00:00Z",
      "predictionHorizonDays": 30,
      "modelVersion": "com01-churn-v2.4",
      "pipelineVersion": "com01-gold-v1.8",
      "thresholdPolicyId": "COM01-RISK-BANDS",
      "thresholdPolicyVersion": "v3",
      "churnDefinitionId": "COM01-30D-CHURN-v2",
      "qualityGateStatus": "PASS",
      "runStatus": "PUBLISHED",
      "failureReason": null,
      "predictions": [
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10004287",
          "churnProbability": 0.91,
          "calibratedChurnProbability": 0.91,
          "riskBand": "HIGH",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10001734",
          "churnProbability": 0.88,
          "calibratedChurnProbability": 0.88,
          "riskBand": "HIGH",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10006519",
          "churnProbability": 0.85,
          "calibratedChurnProbability": 0.85,
          "riskBand": "HIGH",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "recharge-lapsing",
          "microSegmentName": "Recharge lapsing",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10002461",
          "churnProbability": 0.81,
          "calibratedChurnProbability": 0.81,
          "riskBand": "HIGH",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10008730",
          "churnProbability": 0.77,
          "calibratedChurnProbability": 0.77,
          "riskBand": "HIGH",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "usage-declining",
          "microSegmentName": "Usage declining",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10003902",
          "churnProbability": 0.74,
          "calibratedChurnProbability": 0.74,
          "riskBand": "HIGH",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10005648",
          "churnProbability": 0.42,
          "calibratedChurnProbability": 0.42,
          "riskBand": "MEDIUM",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "low-engagement",
          "microSegmentName": "Low engagement",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10007315",
          "churnProbability": 0.26,
          "calibratedChurnProbability": 0.26,
          "riskBand": "LOW",
          "primaryReason": "Declining data usage",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10009184",
          "churnProbability": 0.3,
          "calibratedChurnProbability": 0.3,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "others",
          "microSegmentName": "Others",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10001109",
          "churnProbability": 0.34,
          "calibratedChurnProbability": 0.34,
          "riskBand": "LOW",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "high-value-active",
          "microSegmentName": "High-value active",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10008462",
          "churnProbability": 0.35,
          "calibratedChurnProbability": 0.35,
          "riskBand": "LOW",
          "primaryReason": "Price-plan mismatch",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10002856",
          "churnProbability": 0.29,
          "calibratedChurnProbability": 0.29,
          "riskBand": "LOW",
          "primaryReason": "Contract nearing expiry",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        },
        {
          "businessLine": "Prepaid",
          "microSegmentId": "new-subscribers",
          "microSegmentName": "New subscribers",
          "microSegmentVersion": "COM01-PREPAID-SEG-v1",
          "scoringRunId": "COM01-20260922-01",
          "serviceInstanceId": "SVC-10009764",
          "churnProbability": 0.73,
          "calibratedChurnProbability": 0.73,
          "riskBand": "HIGH",
          "primaryReason": "Repeated service disruptions",
          "modelVersion": "com01-churn-v2.4",
          "pipelineVersion": "com01-gold-v1.8",
          "dataAsOfTs": "2026-09-22T00:00:00Z"
        }
      ]
    }
  ],
  "failedRun": {
    "businessLine": "Prepaid",
    "scoringRunId": "COM01-20260929-01",
    "scoredAtTs": "2026-09-29T01:20:00Z",
    "dataAsOfTs": "2026-09-29T00:00:00Z",
    "predictionHorizonDays": 30,
    "modelVersion": "com01-churn-v2.4",
    "pipelineVersion": "com01-gold-v1.8",
    "thresholdPolicyId": "COM01-RISK-BANDS",
    "thresholdPolicyVersion": "v3",
    "churnDefinitionId": "COM01-30D-CHURN-v2",
    "qualityGateStatus": "FAIL",
    "runStatus": "REJECTED",
    "failureReason": "Prediction completeness below the COM01 publication threshold",
    "predictions": [
      {
        "businessLine": "Prepaid",
        "microSegmentId": "recharge-lapsing",
        "microSegmentName": "Recharge lapsing",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10004287",
        "churnProbability": 0.97,
        "calibratedChurnProbability": 0.97,
        "riskBand": "HIGH",
        "primaryReason": "Contract nearing expiry",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "usage-declining",
        "microSegmentName": "Usage declining",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10001734",
        "churnProbability": 0.95,
        "calibratedChurnProbability": 0.95,
        "riskBand": "HIGH",
        "primaryReason": "Declining data usage",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "low-engagement",
        "microSegmentName": "Low engagement",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10006519",
        "churnProbability": 0.93,
        "calibratedChurnProbability": 0.93,
        "riskBand": "HIGH",
        "primaryReason": "Repeated service disruptions",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "recharge-lapsing",
        "microSegmentName": "Recharge lapsing",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10002461",
        "churnProbability": 0.91,
        "calibratedChurnProbability": 0.91,
        "riskBand": "HIGH",
        "primaryReason": "Price-plan mismatch",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "high-value-active",
        "microSegmentName": "High-value active",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10008730",
        "churnProbability": 0.89,
        "calibratedChurnProbability": 0.89,
        "riskBand": "HIGH",
        "primaryReason": "Price-plan mismatch",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "usage-declining",
        "microSegmentName": "Usage declining",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10003902",
        "churnProbability": 0.87,
        "calibratedChurnProbability": 0.87,
        "riskBand": "HIGH",
        "primaryReason": "Declining data usage",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "others",
        "microSegmentName": "Others",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10005648",
        "churnProbability": 0.85,
        "calibratedChurnProbability": 0.85,
        "riskBand": "HIGH",
        "primaryReason": "Contract nearing expiry",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "low-engagement",
        "microSegmentName": "Low engagement",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10007315",
        "churnProbability": 0.83,
        "calibratedChurnProbability": 0.83,
        "riskBand": "HIGH",
        "primaryReason": "Declining data usage",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      },
      {
        "businessLine": "Prepaid",
        "microSegmentId": "new-subscribers",
        "microSegmentName": "New subscribers",
        "microSegmentVersion": "COM01-PREPAID-SEG-v1",
        "scoringRunId": "COM01-20260929-01",
        "serviceInstanceId": "SVC-10009184",
        "churnProbability": 0.8,
        "calibratedChurnProbability": 0.8,
        "riskBand": "HIGH",
        "primaryReason": "Price-plan mismatch",
        "modelVersion": "com01-churn-v2.4",
        "pipelineVersion": "com01-gold-v1.8",
        "dataAsOfTs": "2026-09-29T00:00:00Z"
      }
    ]
  },
  "interventions": [
    {
      "interventionId": "RET-001",
      "serviceInstanceId": "SVC-10004287",
      "businessLine": "Prepaid",
      "supportedBy": "Sentinel",
      "trackedAtTs": "2026-09-03T00:00:00Z"
    },
    {
      "interventionId": "RET-002",
      "serviceInstanceId": "SVC-10001734",
      "businessLine": "Prepaid",
      "supportedBy": "Sentinel",
      "trackedAtTs": "2026-09-04T00:00:00Z"
    },
    {
      "interventionId": "RET-003",
      "serviceInstanceId": "SVC-10008730",
      "businessLine": "Prepaid",
      "supportedBy": "Sentinel",
      "trackedAtTs": "2026-09-10T00:00:00Z"
    }
  ],
  "outcomes": [
    {
      "interventionId": "RET-001",
      "serviceInstanceId": "SVC-10004287",
      "businessLine": "Prepaid",
      "windowStartTs": "2026-09-03T00:00:00Z",
      "windowEndTs": "2026-09-19T00:00:00Z",
      "status": "RETAINED"
    },
    {
      "interventionId": "RET-002",
      "serviceInstanceId": "SVC-10001734",
      "businessLine": "Prepaid",
      "windowStartTs": "2026-09-04T00:00:00Z",
      "windowEndTs": "2026-09-20T00:00:00Z",
      "status": "RETAINED"
    },
    {
      "interventionId": "RET-003",
      "serviceInstanceId": "SVC-10008730",
      "businessLine": "Prepaid",
      "windowStartTs": "2026-09-10T00:00:00Z",
      "windowEndTs": "2026-09-26T00:00:00Z",
      "status": "RETAINED"
    }
  ]
};
