'use strict';
(() => {
  const api='http://127.0.0.1:8765', content=document.querySelector('#content');
  let token='', connected=false, tab='overview', snapshot=null, timer=null;
  const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pct=v=>typeof v==='number'?(v*100).toFixed(2)+'%':'—';
  const table=(heads,rows)=>`<div class="panel table-wrap"><table><thead><tr>${heads.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const steps=[['Dataset identity','Verify source and train/validation checksums'],['Feature correctness','Correct availability timestamps and verify Python/SQL parity'],['Data validation','Check labels, identifiers, time ordering and numeric features'],['Development training','Train candidates and calibrate on earlier development data'],['Performance evidence','Evaluate by validation period and action budget'],['Model qualification','Review against acceptance criteria agreed before evaluation'],['Primary OOT','Separate one-time acceptance; unavailable in this development runner'],['Gold publication','Approved immutable production pipeline; engine integration pending'],['Studio reconciliation','Read latest published PASS run; integration pending']];
  async function request(path,options={}){const r=await fetch(api+path,{...options,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json();if(!r.ok)throw Error(data.error||'Runner request failed');return data;}
  function render(){
    const d=snapshot?.dataset, runs=snapshot?.runs||[];
    if(tab==='overview')content.innerHTML=table(['Gate','Status','Evidence / next action'],steps.map(([n,h],i)=>[escape(n),`<span class="status neutral">${i===0&&d?'Verified hashes':i===2&&d?'Validated':i===3&&runs.some(r=>r.status==='COMPLETED')?'Executed':i===4&&runs.some(r=>r.metrics?.length)?'Recorded':'Pending'}</span>`,escape(h)]));
    if(tab==='datasets')content.innerHTML=`<h2>Historical development asset</h2><p class="section-sub">The service reads a configured local asset. No dataset is uploaded to GitHub or Sentinel.</p>${d?table(['Field','Value'],Object.entries(d).map(([k,v])=>[escape(k),escape(typeof v==='object'?JSON.stringify(v):v)])):'<div class="panel empty"><h2>No verified dataset</h2><p>Connect the runner with a dataset manifest. The blind 10K is not a training input.</p></div>'}`;
    if(tab==='runs')content.innerHTML=`<h2>Development runs</h2><p class="section-sub">Selection uses the top 10% per validation date. Accuracy is also shown for that action policy.</p><div class="actions"><button id="start" class="button primary" ${!connected||!d||runs.some(r=>r.status==='RUNNING')?'disabled':''}>Run development pipeline</button></div>${runs.map(r=>`<section class="panel training-panel"><h3>${escape(r.id)} · ${escape(r.status)}</h3><p>${escape(r.stage)}</p>${r.metrics?.length?table(['Model / period','Accuracy','No-churn baseline','Precision','Recall','Lift','PR-AUC','Brier'],r.metrics.map(m=>[escape(m.model+' / '+m.period),pct(m.accuracy),pct(m.baseline_accuracy),pct(m.precision),pct(m.recall),m.lift.toFixed(2),m.pr_auc.toFixed(4),m.brier.toFixed(4)])):''}<p class="metric-note">${escape(r.acceptance||'Development evidence only. No model has been accepted or published.')}</p><pre>${escape((r.log||[]).join('\n'))}</pre></section>`).join('')||'<p>No training runs yet.</p>'}`;
    if(tab==='artifacts')content.innerHTML=`<h2>Versioned artifacts</h2><p class="section-sub">Only files produced by this local runner can be downloaded. Model upload to Sentinel is not enabled yet.</p>${table(['Run','Artifact','SHA256',''],runs.flatMap(r=>(r.artifacts||[]).map(a=>[escape(r.id),escape(a.name),escape(a.sha256),`<button class="button" data-download="${escape(r.id+'/'+a.name)}">Download</button>`])))}`;
    if(tab==='integration')content.innerHTML=table(['Connection','Status','Required evidence'],[['Sentinel dev','Not connected','Verify documented model registration, package and publication APIs'],['newchurn10','Comparison pending','Reconcile E7 artifact, serving wrapper and 6,666-service population'],['OOT / blind scoring','Blocked','Separate acceptance and custodian workflow'],['Gold → Studio','Not connected','Accepted model, immutable pipeline, published PASS run and reconciled totals']]);
  }
  async function refresh(){snapshot=await request('/api/status');document.querySelector('#error').textContent=snapshot.dataset_error||'';render();}
  function fail(e){document.querySelector('#error').textContent=e.message;}
  document.querySelector('#connect').onclick=async()=>{try{clearInterval(timer);token=document.querySelector('#token').value;await refresh();connected=true;document.querySelector('#token').value='';document.querySelector('#connection').textContent='Connected to local development runner';document.querySelector('#disconnect').disabled=false;render();timer=setInterval(()=>refresh().catch(fail),4000);}catch(e){connected=false;token='';snapshot=null;render();fail(e);}};
  document.querySelector('#disconnect').onclick=()=>{clearInterval(timer);timer=null;token='';connected=false;snapshot=null;document.querySelector('#connection').textContent='Disconnected';document.querySelector('#disconnect').disabled=true;render();};
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>t.classList.toggle('active',t===b));render();});
  content.onclick=async e=>{try{if(e.target.id==='start'){await request('/api/runs',{method:'POST',body:'{}'});await refresh();}if(e.target.dataset.download){const path=e.target.dataset.download;const r=await fetch(api+'/api/artifacts/'+path,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Download failed');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=path.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(err){fail(err);}};
  window.addEventListener('pagehide',()=>{clearInterval(timer);token='';});render();
})();
