'use strict';
(() => {
  const api=location.origin, content=document.querySelector('#content');
  let connected=false, tab='overview', snapshot=null, timer=null;
  const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pct=v=>typeof v==='number'?(v*100).toFixed(2)+'%':'—';
  const table=(heads,rows)=>`<div class="panel table-wrap"><table><thead><tr>${heads.map(h=>`<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const steps=[['Dataset identity','Verify source and train/validation checksums'],['Feature correctness','Correct availability timestamps and verify Python/SQL parity'],['Data validation','Check labels, identifiers, time ordering and numeric features'],['Development training','Train candidates and calibrate on earlier development data'],['Performance evidence','Evaluate by validation period and action budget'],['Model qualification','Review against acceptance criteria agreed before evaluation'],['Primary OOT','Separate one-time acceptance; unavailable in this development runner'],['Gold publication','Approved immutable production pipeline; engine integration pending'],['Studio reconciliation','Training console integrated; published Mart data reconciliation pending']];
  async function request(path,options={}){const r=await fetch(api+path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(!r.headers.get('Content-Type')?.includes('application/json'))throw Error('Open Studio through the COM01 service to use training. This static preview has no training backend.');const data=await r.json();if(!r.ok){if(data.connection){snapshot={...(snapshot||{}),engine:data.connection};render();}throw Error(data.error||'Runner request failed');}return data;}
  function render(){
    const d=snapshot?.dataset, runs=snapshot?.runs||[];
    const stagingRun=document.querySelector('#stage-run')?.value||'', stagingModel=document.querySelector('#stage-model')?.value||'XGB';
    if(tab==='overview')content.innerHTML=table(['Gate','Status','Evidence / next action'],steps.map(([n,h],i)=>[escape(n),`<span class="status neutral">${i===0&&d?'Verified hashes':i===1&&d?'Local SQL verified':i===2&&d?'Validated':i===3&&runs.some(r=>r.status==='COMPLETED')?'Executed':i===4&&runs.some(r=>r.metrics?.length)?'Recorded':'Pending'}</span>`,escape(h)]));
    if(tab==='datasets')content.innerHTML=`<h2>Historical development asset</h2><p class="section-sub">The service reads a configured local asset. No dataset is uploaded to GitHub or Sentinel.</p>${d?table(['Field','Value'],Object.entries(d).map(([k,v])=>[escape(k),escape(typeof v==='object'?JSON.stringify(v):v)])):'<div class="panel empty"><h2>No verified dataset</h2><p>Connect the runner with a dataset manifest. The blind 10K is not a training input.</p></div>'}`;
    if(tab==='runs')content.innerHTML=`<h2>Development runs</h2><p class="section-sub">Classification accuracy uses a threshold frozen on calibration. Precision, recall and lift below use the top 10% per date.</p><div class="actions"><button id="start" class="button primary" ${!connected||!d||runs.some(r=>r.status==='RUNNING')?'disabled':''}>Run development pipeline</button></div>${runs.map(r=>`<section class="panel training-panel"><h3>${escape(r.id)} · ${escape(r.status)}</h3><p>${escape(r.stage)}</p>${r.staging?`<p>Sentinel: ${escape(r.staging.status)} · ${escape(r.staging.engine_runtime_parity)}</p>`:''}${r.metrics?.length?table(['Model / period','Accuracy','No-churn baseline','Precision','Recall','Lift','PR-AUC','Brier'],r.metrics.map(m=>[escape(m.model+' / '+(m.period || 'All validation dates')),pct(m.accuracy),pct(m.baseline_accuracy),pct(m.top10.precision),pct(m.top10.recall),m.top10.lift.toFixed(2),m.pr_auc_average_precision.toFixed(4),m.brier.toFixed(4)])):''}<p class="metric-note">${escape(r.acceptance||'Development evidence only. No model has been accepted or published.')}</p><pre>${escape((r.log||[]).join('\n'))}</pre></section>`).join('')||'<p>No training runs yet.</p>'}`;
    if(tab==='artifacts')content.innerHTML=`<h2>Versioned artifacts</h2><p class="section-sub">Only files produced by this local runner can be downloaded. Use Sentinel integration to upload a completed serving export to STAGING.</p>${table(['Run','Artifact','SHA256',''],runs.flatMap(r=>(r.artifacts||[]).map(a=>[escape(r.id),escape(a.name),escape(a.sha256),`<button class="button" data-download="${escape(r.id+'/'+a.name)}">Download</button>`])))}`;
    if(tab==='integration'){
      const final=snapshot?.final_evaluation, m=final?.metrics;
      content.innerHTML=table(['Connection / gate','Status'],[['Sentinel SDK',escape(snapshot?.engine?.status||'NOT_CONNECTED')],['Model production qualification','Pending approval'],['Gold pipeline / Studio totals','Pending connected verification']])+`<button class="button" id="engine-connect" ${!connected?'disabled':''}>Verify Sentinel connection</button>`+(m?table(['Frozen final metric','Value'],[['Synthetic acceptance',escape(final.status)],['ROC-AUC',m.classification.roc_auc.toFixed(4)],['Average precision',m.classification.pr_auc_average_precision.toFixed(4)],['Classification accuracy',pct(m.classification.accuracy)],['No-churn accuracy',pct(m.no_churn_accuracy)],['Top 10% recall',pct(m.campaign_top10pct.recall)],['Top 10% lift',m.campaign_top10pct.lift.toFixed(2)],['Engine parity',escape(final.engine_parity)]]):'<p>Attach hashed final evaluation evidence on the runner host.</p>')+`<h2>Staging upload</h2><p>Completed serving exports only. Configure a separate experiment model, version and reviewed Silver query on the host. Live Test and checker approval remain required.</p><label>Completed run <select id="stage-run">${runs.filter(r=>r.status==='COMPLETED').map(r=>`<option value="${escape(r.id)}" ${r.id===stagingRun?'selected':''}>${escape(r.id)}</option>`).join('')}</select></label><label>Model <select id="stage-model">${['XGB','LR','CAT','LGBM'].map(m=>`<option ${m===stagingModel?'selected':''}>${m}</option>`).join('')}</select></label><button class="button" id="stage" ${!connected||!runs.some(r=>r.status==='COMPLETED')?'disabled':''}>Upload to STAGING</button>`;
    }
  }
  async function refresh(){const next=await request('/api/status');const changed=JSON.stringify(snapshot)!==JSON.stringify(next);snapshot=next;document.querySelector('#error').textContent=snapshot.dataset_error||'';if(changed)render();}
  function fail(e){document.querySelector('#error').textContent=e.message;}
  document.querySelector('#connect').onclick=async()=>{try{clearInterval(timer);await refresh();connected=true;document.querySelector('#connection').textContent='Connected to the Studio development service · Sentinel status is shown in the integration tab';document.querySelector('#disconnect').disabled=false;render();timer=setInterval(()=>refresh().catch(e=>{clearInterval(timer);connected=false;document.querySelector('#connection').textContent='Connection lost — refresh evidence to reconnect';render();fail(e);}),15000);}catch(e){connected=false;snapshot=null;document.querySelector('#connection').textContent='Service unavailable — training actions disabled';document.querySelector('#disconnect').disabled=true;render();fail(e);}};
  document.querySelector('#disconnect').onclick=async()=>{try{await request('/api/logout',{method:'POST',body:'{}'});location.reload();clearInterval(timer);timer=null;connected=false;snapshot=null;document.querySelector('#connection').textContent='Disconnected';document.querySelector('#disconnect').disabled=true;render();}catch(e){fail(e);}};
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-selected',String(t===b));});render();});
  content.onclick=async e=>{try{if(e.target.id==='engine-connect'){await request('/api/engine/connect',{method:'POST',body:'{}'});await refresh();}if(e.target.id==='stage'){await request('/api/engine/stage',{method:'POST',body:JSON.stringify({run:document.querySelector('#stage-run').value,model:document.querySelector('#stage-model').value})});await refresh();}if(e.target.id==='start'){await request('/api/runs',{method:'POST',body:'{}'});await refresh();}if(e.target.dataset.download){const path=e.target.dataset.download;const r=await fetch(api+'/api/artifacts/'+path,{credentials:'same-origin'});if(!r.ok)throw Error('Download failed');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=path.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}catch(err){fail(err);}};
  window.addEventListener('pagehide',()=>{clearInterval(timer);});render();document.querySelector('#connect').click();
})();


